function tracks=tracks_h52mat(filepath,varargin)

% tracks=tracks_h52mat(filepath,varargin)
%
% 03/2020 - Thomas Basset
%
% Return track structure from .h5 files generated by "tracks_mat2h5"
% ____________________________________________________________________
% INPUTS
% filepath : path to .h5 file (without .h5)
% fields   : datasets to read (optional, read all datasets by default)
%
% OUTPUT
% tracks : track structure as "tracks_sample.mat"
% ____________________________________________________________________

%field names except L
if nargin>1
    fields=varargin{1};
else
    info=h5info([filepath '.h5']);
    info=info.Datasets;
    fields=cell(length(info)-1,1);
    c=1;
    for k=1:length(info)
        if ~strcmp(info(k).Name,'L')
            fields{c}=info(k).Name;
            c=c+1;
        end
    end
end

%read data and rearrange per track
L=h5read([filepath '.h5'],'/L');
Ntrack=length(L);
tracks=struct([]);
for k=1:length(fields) %for each field
    fieldk=fields{k};
    tracks_temp=h5read([filepath '.h5'],['/' fieldk]);
    c=1;
    for kt=1:Ntrack %for each track
        temp=L(kt);
        tracks(kt).(fieldk)=tracks_temp(c:c+temp-1);
        c=c+temp;
        if k==length(fields) %save L once
            tracks(kt).L=temp;
        end
    end
end

end