function matches = h52matches(filepath,NbFrames, minFrame,Version)

% 04/2020 - David Dumont (TO UPDATE)
%
% Generates matches array from .h5 file generated by "STM.cpp or stm.py"
%% /!\ 2 version of STM.cpp exist and the file are not ordered the same way.
% For this reason you have to choose the version that correspond to yours
% in order to see the match.
% If you've made the computation after 05/2020, it's the version 2, before
% it's the version 1 (ex: Ra1.51e10_dense_1)
% _________________________________________________________________
% INPUT
% filepath : path to .h5 file (without .h5)
% NbFrames : number of frame within the file
% minFrame : number of the first frame (default = 1)
%
% OUTPUT
% tracks   : array provided by STM
% _________________________________________________________________

if ~exist('minFrame','var')
    minFrame = 1;
end

if ~exist('Version','var')
    Version='V2';
end

%% New version
% Lecture of tracks
if Version=='V2'
    matches=[]
    filename = sprintf('%s.h5',filepath)
    for i=1:NbFrames
        dataset=sprintf('/frame%d_xyze',i);
        data = h5read(filename,dataset);
        if i==1
            matches = cat(2,ones(length(data),1)*(i+minFrame-1),data);
        else
            matches1 = cat(2,ones(length(data),1)*(i+minFrame-1),data);
            matches=cat(1,matches,matches1);
        end
    end
end

%% Old version
if Version=='V1'
    filename = sprintf('%s.h5',filepath);

% Lecture of tracks
    matches = h5read(filename,'/tracks');
end 

end
