function [stitchtraj, stitchingparameters] = h52stitch(filepath,varargin)

% 04/2020 - David Dumont
%
% Generate track structure from .h5 file generated by "Stitching.m"
% _________________________________________________________________
% INPUT
% filepath : path to .h5 file (without .h5)
% fields   : datasets to read (optional)
%
% OUTPUT
% stitchtraj : traj structure with one line per trajectory
% stitchingparameters  : structure containing all stitching parameters.
% _________________________________________________________________

filename = sprintf('%s.h5',filepath);

%% Lecture of stitching parameters
% stitchingparameters.dfmax = h5read(filename,'/stitchingparameters/dfmax');
% stitchingparameters.dxmax = h5read(filename,'/stitchingparameters/dxmax');
% stitchingparameters.dvmax = h5read(filename,'/stitchingparameters/dvmax');
% stitchingparameters.lmin = h5read(filename,'/stitchingparameters/lmin');
stitchingparameters = 0;


%% Lecture of data with size 1 for all trajectory (fields L, ntraj, nbfstitch, nbstitch)
L=h5read(filename,'/L');
ntraj=h5read(filename,'/ntraj');
nbfstitch=h5read(filename,'/nbfstitch');
nbstitch=h5read(filename,'/nbstitch');

stitchtraj = struct('frames',cell(1,length(L)),'nmatch',[],'x',[],'y',[],'z',[],'L',[],'ntraj',[],'nbfstitch',[],'fstitch',[],'dXstitch',[],'dVstitch',[],'dfstitch',[],'nbstitch',[]);

Lcell = num2cell(L);
[stitchtraj.L] = Lcell{:};
ntrajcell = num2cell(ntraj);
[stitchtraj.ntraj] = ntrajcell{:};
nbfstitchcell = num2cell(nbfstitch);
[stitchtraj.nbfstitch] = nbfstitchcell{:};
nbstitchcell = num2cell(nbstitch);
[stitchtraj.nbstitch] = nbstitchcell{:};

%% Lecture of data whose size is given by dataset '/L' (fields frames,nmatch,x,y,z)
frames=h5read(filename,'/frames');
nmatch=h5read(filename,'/nmatch');
x=h5read(filename,'/x');
y=h5read(filename,'/y');
z=h5read(filename,'/z');

c=1;
for kt =1:length(L)
    j=L(kt);
    stitchtraj(kt).frames = frames(c:c+j-1);
    stitchtraj(kt).nmatch = nmatch(c:c+j-1);
    stitchtraj(kt).x = x(c:c+j-1);
    stitchtraj(kt).y = y(c:c+j-1);
    stitchtraj(kt).z = z(c:c+j-1);
    c=c+j;
end

%% Lecture of data whose size is given by nbfstitch (field fstitch)
fstitch=h5read(filename,'/fstitch');
c=1;
for kt=1:length(L)
    jfstitch=nbfstitch(kt);
    if jfstitch==0
        stitchtraj(kt).fstitch = [];
    else
        stitchtraj(kt).fstitch = fstitch(c:c+jfstitch-1);
        c=c+jfstitch;
    end
end

%% Lecture of data whose size is given by nbstitch (field dfstitch, dXstitch, dVstitch)
dfstitch=h5read(filename,'/dfstitch');
dXstitch=h5read(filename,'/dXstitch');
dVstitch=h5read(filename,'/dVstitch');

c=1;
d=1;
for kt=1:length(L)
    jstitch=nbstitch(kt);
    if jstitch~=0
        stitchtraj(kt).dfstitch = dfstitch(c:c+jstitch-1);
        stitchtraj(kt).dXstitch = dXstitch(c:c+jstitch-1);
        stitchtraj(kt).dVstitch = dVstitch(d:d+3*jstitch-1);
%         stitchtraj(kt).dVstitch = dVstitch(c:c+jstitch-1);
        c=c+jstitch;
        d=d+3*jstitch;
    end
end

end