function [tracks,trackingparameters]=h52tracks(filepath,varargin)

% 03/2020 - Thomas Basset
%
% Generate track structure from .h5 file generated by "tracks2h5.m"
% _________________________________________________________________
% INPUT
% filepath : path to .h5 file (without .h5)
% fields   : datasets to read (optional)
%
% OUTPUT
% tracks             : track structure with one line per track
% trackingparameters : structure containing all tracking parameters
% _________________________________________________________________

%field names
if nargin>1
    fields=varargin{1};
else
    filename = sprintf('%s.h5',filepath);
    info=h5info(filename);
    data=info.Datasets;
    fields=cell(length(data)-2,1);
    c=1;
    for k=1:length(data)
        if (~strcmp(data(k).Name,'ntraj') && ~strcmp(data(k).Name,'L') && ~strcmp(data(k).Name,'/')) %% ntraj and L are int and / is made of tracking parameters loaded later
            fields{c}=data(k).Name;
            c=c+1;
        end
    end
end

%read data and rearrange per pair
L=h5read(filename,'/L');
ntraj=h5read(filename,'/ntraj');
Ntraj=length(L);
tracks=struct([]);
for k=1:length(fields) %for each field
    fieldk=fields{k};
    tracks_temp=h5read(filename,['/' fieldk]);
    c=1;
    for kt=1:Ntraj%for each track
        temp=L(kt);
        tracks(kt).(fieldk)=tracks_temp(c:c+temp-1);
        c=c+temp;
        if k==length(fields) %save L once
            tracks(kt).L=temp;
            tracks(kt).ntraj=ntraj(kt);
        end
    end
end

trackingparameters=0;
% % Loading of tracking parameters
% trackingparameters.maxdist=h5read(filename,'/trackingparameters/maxdist');
% trackingparameters.lmin=h5read(filename,'/trackingparameters/lmin');
% trackingparameters.flag_pred=h5read(filename,'/trackingparameters/flag_pred');
% trackingparameters.npriormax=h5read(filename,'/trackingparameters/npriormax');
% trackingparameters.flag_conf=h5read(filename,'/trackingparameters/flag_conf');

end